name: Tag
on:
  release:
    types:
      - published
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: T
        run: echo ${GITHUB_REF#refs/*/}
      - name: T2
        run: echo ${GITHUB_REF_NAME}
